--- 
- 
  become: true
  hosts: all
  name: Playbook
  tasks: 
    - 
      name: "ensure apache is at the latest version"
      yum: 
        name: httpd
        state: latest
    - 
      name: "ensure apache is running"
      service: 
        name: httpd
        state: started
    - 
      name: "install "
      yum: 
        name: git
        state: latest
